package edu.wctc.registration.twofactorauth;

import org.springframework.security.authentication.AuthenticationDetailsSource;
import org.springframework.security.web.authentication.WebAuthenticationDetails;
import org.springframework.stereotype.Component;

import javax.servlet.http.HttpServletRequest;

@Component
public class TwoFactorAuthenticationDetailsSource implements AuthenticationDetailsSource<HttpServletRequest, WebAuthenticationDetails> {
    /*
     * Just like regular authentication details, but also includes the
     * 2FA code generated by Google Authenticator
     */
    @Override
    public WebAuthenticationDetails buildDetails(HttpServletRequest context) {
        return new TwoFactorAuthenticationDetails(context);
    }
}
