package edu.wctc.registration.twofactorauth;

import org.springframework.security.web.authentication.WebAuthenticationDetails;

import javax.servlet.http.HttpServletRequest;

/*
 * Just like regular authentication details, but also includes the
 * 2FA code generated by Google Authenticator
 */
public class TwoFactorAuthenticationDetails extends WebAuthenticationDetails {

    private final String verificationCode;

    public TwoFactorAuthenticationDetails(HttpServletRequest request) {
        super(request);
        verificationCode = request.getParameter("code");
    }

    public String getVerificationCode() {
        return verificationCode;
    }
}
